import { test, expect } from '../fixtures/test'
import { demoItem, openDemo, t } from '../helpers/demo'

for (const kind of ['input', 'textarea'] as const) {
  test(`${kind} 真实时钟连续键入后立即清空并重新输入`, async ({ page }) => {
    await openDemo(page, kind, `.page-${kind} ${kind}`)
    const item = demoItem(page, t(kind === 'input' ? 'qing-kong-an-niu' : 'qing-kong-an-niu-he-zi-shu-xian-zhi'))
    const field = item.locator(kind)
    await field.fill('')
    await field.pressSequentially('pending input')
    await item.locator(`.wd-${kind}__clear`).click()
    await expect(field).toHaveValue('')
    await field.pressSequentially('new input')
    await field.press('Tab')
    await expect(field).toHaveValue('new input')
    if (kind === 'textarea') await expect(item.locator('.wd-textarea__count')).toHaveText('9/120')
  })

  test(`${kind} 节流期间清空后旧输入不会回填`, async ({ page }) => {
    await page.clock.install()
    await openDemo(page, kind, `.page-${kind} ${kind}`)
    const item = demoItem(page, t(kind === 'input' ? 'qing-kong-an-niu' : 'qing-kong-an-niu-he-zi-shu-xian-zhi'))
    const field = item.locator(kind)
    await field.fill('first')
    await page.clock.runFor(200)
    await item.locator(`.wd-${kind}__clear`).hover()
    await page.clock.pauseAt(new Date(Date.now() + 10000))
    await field.fill('second')
    await field.fill('pending')
    await item.locator(`.wd-${kind}__clear`).click()
    await page.clock.runFor(300)
    await expect(field).toHaveValue('')
    await field.fill('new')
    await page.clock.runFor(300)
    await expect(field).toHaveValue('new')
    if (kind === 'textarea') await expect(item.locator('.wd-textarea__count')).toHaveText('3/120')
  })
  test(`${kind} 清空后立即重新输入不会丢失新文字`, async ({ page }) => {
    await page.clock.install()
    await openDemo(page, kind, `.page-${kind} ${kind}`)
    const item = demoItem(page, t(kind === 'input' ? 'qing-kong-an-niu' : 'qing-kong-an-niu-he-zi-shu-xian-zhi'))
    const field = item.locator(kind)
    await field.fill('first')
    await page.clock.runFor(200)
    await item.locator(`.wd-${kind}__clear`).hover()
    await page.clock.pauseAt(new Date(Date.now() + 10000))
    await field.fill('second')
    await field.fill('pending')
    await item.locator(`.wd-${kind}__clear`).click()
    await field.fill('新输入')
    await page.clock.runFor(300)
    await expect(field).toHaveValue('新输入')
    if (kind === 'textarea') await expect(item.locator('.wd-textarea__count')).toHaveText('3/120')
  })

  test(`${kind} 连续输入的父级回显不取消最新输入`, async ({ page }) => {
    await page.clock.install()
    await openDemo(page, kind, `.page-${kind} ${kind}`)
    const item = demoItem(page, t(kind === 'input' ? 'qing-kong-an-niu' : 'qing-kong-an-niu-he-zi-shu-xian-zhi'))
    const field = item.locator(kind)
    await field.fill('a')
    await page.clock.runFor(200)
    await page.clock.pauseAt(new Date(Date.now() + 10000))
    for (const value of ['ab', 'abc', 'abcd']) await field.fill(value)
    await page.clock.runFor(300)
    await expect(field).toHaveValue('abcd')
    if (kind === 'textarea') await expect(item.locator('.wd-textarea__count')).toHaveText('4/120')
  })
}

test('输入后立即点击提交使用最新表单值', async ({ page }) => {
  await page.clock.install()
  await openDemo(page, 'form', '.page-form .wd-form')
  const item = demoItem(page, t('ji-chu-biao-dan'))
  await item.locator('input').nth(0).fill('final')
  await item.locator('input').nth(1).fill('old')
  await page.clock.runFor(200)
  await item.locator('.wd-button').hover()
  await page.clock.pauseAt(new Date(Date.now() + 10000))
  await item.locator('input').nth(1).fill('intermediate')
  await item.locator('input').nth(1).fill('final')
  await item.locator('.wd-button').click()
  await page.clock.runFor(300)
  await expect(page.locator('.wd-toast:visible')).toContainText(t('ti-jiao-cheng-gong'))
  await expect(item.locator('.wd-form-item__error-message')).toHaveCount(0)
})

test('中文组合输入期间不更新计数，结束后同步并可清空', async ({ page }) => {
  await page.clock.install()
  await openDemo(page, 'textarea', '.page-textarea textarea')
  const item = demoItem(page, t('qing-kong-an-niu-he-zi-shu-xian-zhi'))
  const field = item.locator('textarea')
  await field.fill('')
  await page.clock.runFor(200)
  // 合成 composition 事件验证事件契约，不能替代真机输入法验证。
  await field.dispatchEvent('compositionstart', { data: '' })
  await field.evaluate((element) => {
    const textarea = element as HTMLTextAreaElement
    textarea.value = '中文'
    textarea.dispatchEvent(new InputEvent('input', { bubbles: true, data: '中文', inputType: 'insertCompositionText', isComposing: true }))
  })
  await page.clock.runFor(200)
  await expect(item.locator('.wd-textarea__count')).toHaveText('0/120')
  await field.dispatchEvent('compositionend', { data: '中文' })
  await page.clock.runFor(200)
  await expect(field).toHaveValue('中文')
  await expect(item.locator('.wd-textarea__count')).toHaveText('2/120')
  await item.locator('.wd-textarea__clear').click()
  await expect(field).toHaveValue('')
})
