import { test, expect } from '../fixtures/test'
import { fillUniField, demoItem, formItem, openDemo, t } from '../helpers/demo'

test.beforeEach(async ({ page }) => {
  await page.clock.install()
})

test('基础表单空值与跨字段校验，修正后提交成功', async ({ page }) => {
  await openDemo(page, 'form', '.page-form .wd-form')
  const item = demoItem(page, t('ji-chu-biao-dan'))
  await item.locator('.wd-button').click()
  await expect(item.locator('.wd-form-item__error-message')).toHaveText([t('qing-shu-ru-wai-bi-ba-bu'), t('qing-shu-ru-sha-ka-la-ka')])
  await fillUniField(page, item.locator('input').nth(0), 'wot')
  await fillUniField(page, item.locator('input').nth(1), 'ui')
  await item.locator('.wd-button').click()
  await expect(item.locator('.wd-form-item__error-message')).toHaveText([
    t('liang-ge-shu-ru-kuang-de-nei-rong-bi-xu-yi-zhi'),
    t('liang-ge-shu-ru-kuang-de-nei-rong-bi-xu-yi-zhi')
  ])
  await fillUniField(page, item.locator('input').nth(1), 'wot')
  await item.locator('.wd-button').click()
  await expect(page.locator('.wd-toast:visible')).toContainText(t('ti-jiao-cheng-gong'))
  await expect(item.locator('.wd-form-item__error-message')).toHaveCount(0)
})

test('隐藏字段不校验，显示后参加必填校验', async ({ page }) => {
  await openDemo(page, 'form', '.page-form .wd-form')
  const item = demoItem(page, t('yin-cang-zi-duan-xiao-yan'))
  await item.locator('.wd-button').click()
  await expect(page.locator('.wd-toast:visible')).toContainText(t('xiao-yan-tong-guo'))
  await item.locator('.wd-switch').click()
  await item.locator('.wd-button').click()
  await expect(item.locator('.wd-form-item__error-message')).toHaveText(t('qing-shu-ru-yin-cang-zi-duan'))
  await fillUniField(page, item.locator('input').nth(1), 'visible now')
  await item.locator('.wd-button').click()
  await expect(item.locator('.wd-form-item__error-message')).toHaveCount(0)
})

test('父路径 prop 接收嵌套子字段错误', async ({ page }) => {
  await openDemo(page, 'form', '.page-form .wd-form')
  const item = demoItem(page, t('fu-lu-jing-xiao-yan'))
  await item.locator('.wd-button').click()
  await expect(item.locator('.wd-form-item__error-message')).toHaveText(t('qing-shu-ru-yong-hu-ming'))
  await fillUniField(page, item.locator('input'), 'wot-ui')
  await item.locator('.wd-button').click()
  await expect(item.locator('.wd-form-item__error-message')).toHaveCount(0)
  await expect(page.locator('.wd-toast:visible')).toContainText(t('xiao-yan-tong-guo'))
})

for (const engine of ['Zod', '自定义']) {
  test(`动态表单 ${engine} 支持增删字段，reset 清除校验并保留值`, async ({ page }) => {
    await page.goto('/#/subPages/form/demo1')
    const form = page.locator('.wd-form')
    await expect(form.locator('input')).toHaveCount(2)
    if (engine === '自定义') await form.locator('.wd-switch').click()
    await form.locator('.wd-button').getByText(t('tian-jia'), { exact: true }).click()
    await expect(form.locator('input')).toHaveCount(3)
    await form.locator('.wd-button').getByText(t('ti-jiao'), { exact: true }).click()
    await expect(form.locator('.wd-form-item__error-message')).toHaveCount(3)
    await fillUniField(page, form.locator('input').nth(0), 'wot')
    await fillUniField(page, form.locator('input').nth(1), '001')
    await form.locator('.wd-button').getByText(t('shan-chu'), { exact: true }).click()
    await expect(form.locator('input')).toHaveCount(2)
    await form.locator('.wd-button').getByText(t('ti-jiao'), { exact: true }).click()
    await expect(page.locator('.wd-toast:visible')).toContainText(t('xiao-yan-tong-guo'))
    await form.locator('.wd-button').getByText(t('zhong-zhi'), { exact: true }).click()
    await expect(form.locator('input').nth(0)).toHaveValue('wot')
    await expect(form.locator('input').nth(1)).toHaveValue('001')
    await expect(form.locator('.wd-form-item__error-message')).toHaveCount(0)
  })
}

test('字段 blur、change、submit 按各自时机校验', async ({ page }) => {
  await page.goto('/#/subPages/form/demo2')
  const account = formItem(page, t('zhang-hao-blur'))
  await fillUniField(page, account.locator('input'), 'a')
  await expect(account.locator('.wd-form-item__error-message')).toHaveCount(0)
  const remark = formItem(page, t('bei-zhu-change'))
  await fillUniField(page, remark.locator('textarea'), '短')
  await expect(account.locator('.wd-form-item__error-message')).toHaveText(t('zhang-hao-zhi-shao-3-wei'))
  await expect(remark.locator('.wd-form-item__error-message')).toHaveText(t('bei-zhu-zhi-shao-shu-ru-4-ge-zi'))
  await fillUniField(page, remark.locator('textarea'), '四个汉字')
  await expect(remark.locator('.wd-form-item__error-message')).toHaveCount(0)
  const city = formItem(page, t('cheng-shi-submit'))
  await fillUniField(page, city.locator('input'), '北京')
  await fillUniField(page, city.locator('input'), '')
  await page.locator('.page-form-demo2__footer .wd-button').click()
  await expect(city.locator('.wd-form-item__error-message')).toHaveText(t('qing-shu-ru-cheng-shi'))
})

test('复杂表单布局切换保留输入，开关控制条件字段', async ({ page }) => {
  await page.goto('/#/subPages/form/demo3')
  const name = formItem(page, t('you-hui-quan-ming-cheng'))
  await fillUniField(page, name.locator('input'), '秋季优惠')
  await formItem(page, t('biao-dan-xiang-bu-ju')).locator('.wd-switch').click()
  await expect(page.locator('.page-form-demo3__layout-tip')).toHaveText('上下布局')
  await expect(name.locator('input')).toHaveValue('秋季优惠')
  const discount = formItem(page, t('zhe-kou'))
  await expect(discount).toHaveCount(1)
  await formItem(page, t('kai-qi-zhe-kou')).locator('.wd-switch').click()
  await expect(discount).toHaveCount(0)
  await formItem(page, t('kai-qi-zhe-kou')).locator('.wd-switch').click()
  await expect(discount.locator('input')).toHaveValue('1')
})

test('错误展示从 toast 切换为字段 message，修正后成功', async ({ page }) => {
  await page.goto('/#/subPages/form/demo4')
  const submit = page.locator('.page-form-demo4__footer .wd-button')
  await submit.click()
  await expect(page.locator('.wd-form .wd-toast:visible')).toContainText(t('qing-shu-ru-wai-bi-ba-bu'))
  await expect(page.locator('.wd-form-item__error-message')).toHaveCount(0)
  await page.locator('.wd-radio').getByText('message', { exact: true }).click()
  await submit.click()
  await expect(page.locator('.wd-form-item__error-message')).toHaveCount(2)
  await fillUniField(page, page.locator('.wd-form input').nth(0), 'wot')
  await fillUniField(page, page.locator('.wd-form input').nth(1), 'ui')
  await submit.click()
  await expect(page.locator('.wd-form-item__error-message')).toHaveCount(0)
  await expect(page.locator('.wd-toast:visible')).toContainText(t('xiao-yan-tong-guo'))
})

test('表单统一禁用传给输入及选择器，解除后可编辑', async ({ page }) => {
  await page.goto('/#/subPages/form/demo5')
  const name = formItem(page, t('yong-hu-ming')).locator('input')
  await expect(name).not.toBeEditable()
  await expect(formItem(page, t('huo-dong-xi-ze')).locator('textarea')).not.toBeEditable()
  const platform = formItem(page, t('tui-guang-ping-tai'))
  await platform.click()
  await expect(page.locator('.wd-select-picker__popup:visible')).toHaveCount(0)
  await page.locator('.page-form-demo5__switch .wd-switch').click()
  await fillUniField(page, name, 'editable')
  await expect(name).toHaveValue('editable')
  await platform.click()
  await expect(page.locator('.wd-select-picker__popup:visible')).toBeVisible()
})
